### ISSUE TITLE
ERROR:  Missing options -c or -B

### ISSUE THREAD

**Issue by zhuxxyy12** [WeirauchLab/MARIO#1]
I used the command MARIO -dA test.bam -C CONFIG.txt -G SNPposition.txt, and the error appeared to be Missing options -c or -B. I have no idea how to fix it.

**Comment by ernstki** [comment]
Hi, @zhuxxyy12. Please supply a pathname to the peaks for the BAM with the `-c` option.

You can run `MARIO -h | less` to view the help for this.

—Kevin
