### ISSUE TITLE
ERROR: Required file does not exist

### ISSUE THREAD

**Issue by zhuxxyy12** [WeirauchLab/MARIO#2]
I used the command MARIO -dA test.bam -C CONFIG.txt -G SNPposition -c test.bed
the problem appeared to be ERROR: Required file, "/home/mario/Documents/CCHMC_postdoc/Projects/Allele_specific_variants/SDataB_VariantsUsedForEachPhenotype.bed" in option "ANNO_1", does not exist.
I am wondering how to fix this problem.

**Comment by ernstki** [comment]
Hi @zhuxxyy12. You will need to update the line that begins with `ANNO_1 =` in your `CONFIG.txt`. There should be comments beginning with `#` above that line in the config file which provide more information.

At some point, I can update the README to be more clear about this. 

In many cases, though, searching the source code for some part of the error message will give you a hint about what to try next. In this case, [a search for `SDataB_VariantsUsedForEachPhenotype`](https://github.com/WeirauchLab/MARIO/search?q=SDataB_VariantsUsedForEachPhenotype) reveals the origin of that pathname, the subroutine that creates the default config file.

Hope that helps.

—Kevin
